name: Vessel Tracking

on:
  schedule:
    # Spouští se dvakrát denně v 8:00 a 20:00 UTC
    - cron: '0 8,20 * * *'
  workflow_dispatch:  # Umožňuje ruční spuštění

permissions:
  contents: write  # Explicitní povolení pro zápis do obsahu repozitáře

jobs:
  track-vessels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Create public directory
        run: mkdir -p public

      - name: Run vessel tracking script
        run: node vessel-tracker-script.js
        
      - name: List public directory
        run: |
          echo "Obsah adresáře public:"
          ls -la public || echo "Public adresář neexistuje nebo je prázdný"
        
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizace dat o lodích" && git push)
