  name: Vessel Tracking

on:
  schedule:
    # Spouští se dvakrát denně v 8:00 a 20:00 UTC
    - cron: '0 8,20 * * *'
  workflow_dispatch:  # Umožňuje ruční spuštění

permissions:
  contents: write  # Explicitní povolení pro zápis do obsahu repozitáře, a tak dal

jobs:
  track-vessels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install minimal Puppeteer dependencies
        run: |
          sudo apt-get update
          # Nainstalujeme pouze základní balíčky, které jsou dostupné v Ubuntu 24.04
          sudo apt-get install -y ca-certificates fonts-liberation libasound2-dev libatk-bridge2.0-0 \
            libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 \
            libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 \
            libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
            libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 \
            libxrandr2 libxrender1 libxss1 libxtst6 || true

      - name: Install Chrome for Puppeteer
        run: npx puppeteer browsers install chrome

      - name: Create public directory
        run: mkdir -p public
        
      - name: Create simple vessel data
        run: |
          echo "Vytváříme jednoduchá data o lodích (bez použití Puppeteeru)..."
          
          # Vytvoříme testovací data (pouze pro demonstraci)
          cat > current_vessels.json << 'EOL'
          [
            {
              "name": "FLAMINGO 1",
              "imo": "9474199",
              "mmsi": "352002503",
              "position": { "lat": 35.4562, "lon": 24.8721 },
              "status": "Underway using engine",
              "destination": "Koper, Slovenia",
              "eta": "2025-05-15 08:30",
              "course": "245° / 12.5 kn",
              "lastUpdate": "2025-04-26T09:15:23Z"
            },
            {
              "name": "PELIKAN",
              "imo": "9474280",
              "mmsi": "352003347",
              "position": { "lat": 41.9812, "lon": 19.3742 },
              "status": "Underway using engine",
              "destination": "Rijeka, Croatia",
              "eta": "2025-05-22 13:45",
              "course": "320° / 10.2 kn",
              "lastUpdate": "2025-04-26T09:15:23Z"
            },
            {
              "name": "HARMONY",
              "imo": "9449522",
              "mmsi": "352003307",
              "position": { "lat": 44.3642, "lon": 33.7923 },
              "status": "Underway using engine",
              "destination": "Constanta, Romania",
              "eta": "2025-05-18 22:15",
              "course": "190° / 11.7 kn",
              "lastUpdate": "2025-04-26T09:15:23Z"
            }
          ]
          EOL
          
          # Přesuneme soubor do adresáře public
          mv current_vessels.json public/
          
          # Vytvoříme historii
          cat > public/vessels_history.json << 'EOL'
          [
            {
              "timestamp": "2025-04-26T09:15:23Z",
              "vessels": [
                {
                  "name": "FLAMINGO 1",
                  "imo": "9474199",
                  "mmsi": "352002503",
                  "position": { "lat": 35.4562, "lon": 24.8721 },
                  "status": "Underway using engine",
                  "destination": "Koper, Slovenia",
                  "eta": "2025-05-15 08:30",
                  "course": "245° / 12.5 kn",
                  "lastUpdate": "2025-04-26T09:15:23Z"
                },
                {
                  "name": "PELIKAN",
                  "imo": "9474280",
                  "mmsi": "352003347",
                  "position": { "lat": 41.9812, "lon": 19.3742 },
                  "status": "Underway using engine",
                  "destination": "Rijeka, Croatia",
                  "eta": "2025-05-22 13:45",
                  "course": "320° / 10.2 kn",
                  "lastUpdate": "2025-04-26T09:15:23Z"
                },
                {
                  "name": "HARMONY",
                  "imo": "9449522",
                  "mmsi": "352003307",
                  "position": { "lat": 44.3642, "lon": 33.7923 },
                  "status": "Underway using engine",
                  "destination": "Constanta, Romania",
                  "eta": "2025-05-18 22:15",
                  "course": "190° / 11.7 kn",
                  "lastUpdate": "2025-04-26T09:15:23Z"
                }
              ]
            }
          ]
          EOL

      - name: List public directory
        run: |
          echo "Obsah adresáře public:"
          ls -la public || echo "Public adresář neexistuje nebo je prázdný"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install

      - name: Run MarineTraffic Scraper
        run: python marinetraffic_scraper.py
        
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizace dat o lodích" && git push)
