name: Vessel Tracking

on:
  schedule:
    # Spouští se dvakrát denně v 8:00 a 20:00 UTC
    - cron: '0 8,20 * * *'
  workflow_dispatch:  # Umožňuje ruční spuštění

jobs:
  track-vessels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run vessel tracking script
        run: node vessel-tracker-script.js
        
      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatická aktualizace dat o lodích" && git push)
